### ISSUE TITLE
Detach CDROMs

### ISSUE THREAD

**Issue by skpy** [covermymeds/mkvm#23]
PR #22 set `startConnected` to false, but that only takes effect at power-on.

I think we need to also set `cdrom.connectable.connected = false` after [line 288](https://github.com/covermymeds/mkvm/blob/master/lib/vsphere.rb#L288) to ensure that the CD is detached immediately.

There appears to be wild inconsistencies in how long it takes VMware to start the `ReconfigVM_Task` process.  Sometimes it happens immediately, sometimes it happens up to 15 seconds later.  A blanket "sleep 20" seems awfully imprecise.  Should we loop through a "pool, sleep" cycle until the question is presented asking for confirmation to detach the CD?

**Comment by techsource12** [comment]
Are we running 

```
eject
```

on the VM first? Sorry if I am asking dumb questions. We'll avoid the prompt (I think) if we run 'eject' on the VM first.

**Comment by skpy** [comment]
The eject happens shortly after the initial ramdisk is loaded into memory and the anaconda / Kickstart process has kicked off. I actually don't know if `eject` is available in that limited runtime environment. If it is, we could certainly do that as a pre- script.

mkvm won't know when that happens, so we'd still need some level of sleep / delay in mkvm to allow the `eject` to occur.

**Comment by techsource12** [comment]
I guess my question is can we just run the detach as some sort of external post process and save us a lot of agony? Like on a first Puppet check in mixed with a custom fact?

Sent from my VIC 20

On Feb 26, 2016, at 4:57 PM, Scott Merrill <notifications@github.com<mailto:notifications@github.com>> wrote:

The eject happens shortly after the initial ramdisk is loaded into memory and the anaconda / Kickstart process has kicked off. I actually don't know if `eject` is available in that limited runtime environment. If it is, we could certainly do that as a pre- script.

mkvm won't know when that happens, so we'd still need some level of sleep / delay in mkvm to allow the `eject` to occur.


-
Reply to this email directly or view it on GitHub<https://github.com/covermymeds/mkvm/issues/23#issuecomment-189499555>.

This electronic transmission is confidential and intended solely for the addressee(s). If you are not an intended addressee, do not disclose, copy or take any other action in reliance on this transmission. If you have received this transmission in error, please delete it from your system and notify CoverMyMeds LLC at privacy@covermymeds.com. Thank you.

**Comment by adamcstephens** [comment]
This is no longer relevant.
