### ISSUE TITLE
add support for (Anti)Affinity rules

### ISSUE THREAD

**Issue by skpy** [covermymeds/mkvm#6]
Use the vSphere API to create (Anti)Affinity rules for VMs created by mkvm

References:
http://pubs.vmware.com/vsphere-51/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.cluster.AntiAffinityRuleSpec.html

http://pubs.vmware.com/vsphere-51/index.jsp?topic=%2Fcom.vmware.wssdk.apiref.doc%2Fvim.cluster.RuleInfo.html

It looks like we could just add to the "rule" array for the cluster.configuration object, which contains a sequence of the following:

   ClusterAntiAffinityRuleSpec(
     dynamicProperty: [],
     enabled: true,
     key: 803,
     name: "API",
     userCreated: true,
     vm: [VirtualMachine("vm-39122"), VirtualMachine("vm-39124")]
   ),

Note: I don't think we can create these rules preemptively, because the vm element is an array of VM objects. Thus, you can't create the rule until the targets have been instantiated.

**Comment by everestx** [comment]
This was addressed and merged in #21
